# Generated by Django 5.1.1 on 2024-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_workout_end_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
