# Generated by Django 5.1.1 on 2024-10-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_workout_end_time_workout_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_name',
        ),
        migrations.AlterField(
            model_name='workout',
            name='activity_type',
            field=models.CharField(choices=[('Walking', 'Walking at moderate speed (4 km/h)'), ('Jumping Rope', 'Skipping rope, light workout'), ('Running', 'Running at 9.6 km/h'), ('Cycling', 'Cycling at a moderate pace'), ('Weightlifting', 'Light/moderate effort Weight Training')], max_length=50),
        ),
    ]
