# Generated by Django 5.1.1 on 2024-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_workout_workout_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='activity_type',
            field=models.CharField(choices=[('Walking', 'Walking at moderate speed (4 km/h)'), ('Skipping', 'Jumping rope, light workout'), ('Running', 'Running at 9.6 km/h'), ('Cycling', 'Cycling at a moderate pace'), ('Weightlifting', 'Light/moderate effort Weight Training')], max_length=50),
        ),
    ]
